# Generated by Django 5.2.1 on 2025-05-21 13:09

from django.db import migrations


class Migration(migrations.Migration):
    """
    Миграция для удаления поля logo из модели Partner.
    """
    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
    ]
