# Generated by Django 5.2.1 on 2025-06-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0002_remove_partner_logo"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE promo_offer REPLICA IDENTITY FULL;
                ALTER TABLE promo_category REPLICA IDENTITY FULL;
                ALTER TABLE promo_city REPLICA IDENTITY FULL;
                ALTER TABLE promo_partner REPLICA IDENTITY FULL;
                """,
            reverse_sql="""
                ALTER TABLE promo_offer REPLICA IDENTITY DEFAULT;
                ALTER TABLE promo_category REPLICA IDENTITY DEFAULT;
                ALTER TABLE promo_city REPLICA IDENTITY DEFAULT;
                ALTER TABLE promo_partner REPLICA IDENTITY DEFAULT;
                """,
        ),
    ]
